version: '3.7'

services:
  pg:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  py:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    command: sleep infinity
    depends_on:
      - pg
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pg
      - TOX_WORK_DIR=/tmp/tox
    working_dir: /code
    volumes:
    - .:/code
    - /tmp:/root/.cache
