version: '3.7'

services:
  pg:
    # 12 breaks older versions of sqlalchemy so sticking with 11 for now
    # https://github.com/sqlalchemy/sqlalchemy/issues/4463
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  py:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    command: sleep infinity
    depends_on:
      - pg
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pg
    working_dir: /code
    volumes:
    - .:/code
    - /tmp:/root/.cache
